version: '3.1'

services:

  mssql:
    build: ./docker
    restart: on-failure
    environment:
       - ACCEPT_EULA=Y
       - SA_PASSWORD=SuperStrong@Passw0rd
       - SCRIPT_SLEEP=15s
    ports:
       - 1433:1433
    volumes:
      - ./sql:/usr/src/perftest/sql